--HAS PHOTO 1 OR 0
SELECT a.*, 
       CASE WHEN a.DISPENSER_PHOTO IS NOT NULL THEN 1 ELSE 0 END AS HAS_PHOTO
FROM T_RRHH_OCUPATIONAL_HEALTH_DISPENSERS  a;

--BASIC INFO  DISPENSERS
SELECT 
    CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME) AS CompleteName,
    CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME ,' - ', a.DNI) AS CompleteNameWithDni,
    UPPER(CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME)) AS CompleteNameUppercase,
    CASE WHEN a.DISPENSER_PHOTO IS NOT NULL THEN 1 ELSE 0 END AS HasPhoto
FROM 
   T_RRHH_OCUPATIONAL_HEALTH_DISPENSERS  a;

--BASIC INFO MEDICAL STAFF
SELECT    
    CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME) AS FullName,
    CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME, ' ', a.DNI) AS FullNameWithDni,
    CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME, ' ', a.DNI, ' ', a.MEDICAL_STAFF_CODE) AS FullNameWithDniAndCode,
    CASE WHEN a.MEDICAL_STAFF_PHOTO IS NOT NULL THEN 1 ELSE 0 END AS HasPhoto
FROM 
    T_RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF a;


-- ASSIGNMENTS INFO
SELECT a.ENTITY_TYPE,    
       CONCAT(b.FIRST_NAME, ' ', b.LAST_NAME, ' - ', b.DNI) AS CompleteNameWithDni,
       'Dispenser' AS EntityTypeDescription
FROM T_RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS a
INNER JOIN T_RRHH_OCUPATIONAL_HEALTH_DISPENSERS b ON a.IDE_ENTITY = b.IDE_DISPENSER
UNION
SELECT a.ENTITY_TYPE,
       CONCAT(b.FIRST_NAME, ' ', b.LAST_NAME, ' - ', b.DNI, ' - ', b.MEDICAL_STAFF_CODE) AS FullNameWithDniAndCode,
       'Medical Staff' AS EntityTypeDescription
FROM T_RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS a
INNER JOIN T_RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF b ON a.IDE_ENTITY = b.IDE_MEDICAL_STAFF;


--- INFO TO INSERT

-- SELECT    
--     CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME, ' - ', a.DNI, ' - ', a.MEDICAL_STAFF_CODE) AS FullNameWithDniAndCode,
--     'Medical Staff' AS EntityTypeDescription
-- FROM 
--     T_RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF a
-- UNION
-- SELECT 
--     CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME ,' - ', a.DNI) AS CompleteNameWithDni,
--     'Dispenser' AS EntityTypeDescription
-- FROM 
--     T_RRHH_OCUPATIONAL_HEALTH_DISPENSERS a;


--  Total 
SELECT COUNT(*) AS ASIGGNMENTS FROM T_RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS; -- 8
SELECT COUNT(*) AS DISPENSER FROM  T_RRHH_OCUPATIONAL_HEALTH_DISPENSERS;  -- 12 
SELECT COUNT (*) AS MEDICAL FROM T_RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF; -- 15

--Dispenser que estan disponibles  TOTAL
SELECT COUNT(a.IDE_DISPENSER) as Dispemser
FROM T_RRHH_OCUPATIONAL_HEALTH_DISPENSERS a
WHERE NOT EXISTS (
    SELECT 1
    FROM T_RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS b
    WHERE a.IDE_DISPENSER = b.IDE_ENTITY 
); -- 8

--Medical estaff que estan disponibles TOTAL
SELECT COUNT(a.IDE_MEDICAL_STAFF) as Medical 
FROM  T_RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF a
WHERE NOT EXISTS(
    SELECT 1 
    FROM  T_RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS b
    WHERE a.IDE_MEDICAL_STAFF = b.IDE_ENTITY
); -- 11

--TOATL MEDICAL: DISPENSER
SELECT SUM(CountValue) AS TotalSum
FROM  (
    SELECT COUNT(a.IDE_DISPENSER) AS CountValue
    FROM T_RRHH_OCUPATIONAL_HEALTH_DISPENSERS a
    WHERE NOT EXISTS (
        SELECT 1
        FROM T_RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS b
        WHERE a.IDE_DISPENSER = b.IDE_ENTITY
    )
    UNION ALL
    SELECT COUNT(a.IDE_MEDICAL_STAFF) AS CountValue
    FROM T_RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF a
    WHERE NOT EXISTS (
        SELECT 1
        FROM T_RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS b
        WHERE a.IDE_MEDICAL_STAFF = b.IDE_ENTITY
    )
) AS Counts;--19


--Dispenser que estan disponibles  INFO
SELECT CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME ,' - ', a.DNI) AS CompleteNameWithDni,
       'Dispenser' AS EntityTypeDescription
FROM T_RRHH_OCUPATIONAL_HEALTH_DISPENSERS a
WHERE NOT EXISTS (
    SELECT 1
    FROM T_RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS b
    WHERE a.IDE_DISPENSER = b.IDE_ENTITY
);

--Medical estaff que estan disponibles  IFNO
SELECT CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME, ' - ', a.DNI, ' - ', a.MEDICAL_STAFF_CODE) AS FullNameWithDniAndCode,
    'Medical Staff' AS EntityTypeDescription
FROM  T_RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF a
WHERE NOT EXISTS(
    SELECT 1 
    FROM  T_RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS b
    WHERE a.IDE_MEDICAL_STAFF = b.IDE_ENTITY
);



--Dispenser and Medical staff disponibles
SELECT CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME ,' - ', a.DNI) AS CompleteNameWithDni,
       'Dispenser' AS EntityTypeDescription
FROM T_RRHH_OCUPATIONAL_HEALTH_DISPENSERS a
WHERE NOT EXISTS (
    SELECT 1
    FROM T_RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS b
    WHERE a.IDE_DISPENSER = b.IDE_ENTITY)
UNION
SELECT CONCAT(a.FIRST_NAME, ' ', a.LAST_NAME, ' - ', a.DNI, ' - ', a.MEDICAL_STAFF_CODE) AS FullNameWithDniAndCode,
    'Medical Staff' AS EntityTypeDescription
FROM  T_RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF a
WHERE NOT EXISTS(
    SELECT 1 
    FROM  T_RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS b
    WHERE a.IDE_MEDICAL_STAFF = b.IDE_ENTITY
);

SELECT * from  T_RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS;