ALTER TABLE [T_RRHH_OCUPATIONAL_HEALTH_ADMINISTRATION_ROUTES]
ADD [IDE_COMPANY] uniqueidentifier NOT NULL;
GO

-- Agregar la columna IDE_MEDICATION a la tabla T_RRHH_OCUPATIONAL_HEALTH_LOTS
ALTER TABLE T_RRHH_OCUPATIONAL_HEALTH_LOTS
ADD IDE_MEDICATION UNIQUEIDENTIFIER NOT NULL;

-- Crear el índice en la columna IDE_MEDICATION
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_PERSONNEL_index_26] 
ON [T_RRHH_OCUPATIONAL_HEALTH_LOTS] (IDE_MEDICATION);

-- Crear la clave foránea entre T_RRHH_OCUPATIONAL_HEALTH_LOTS e T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS
ALTER TABLE [T_RRHH_OCUPATIONAL_HEALTH_LOTS] 
ADD FOREIGN KEY ([IDE_MEDICATION]) 
REFERENCES [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS] ([IDE_MEDICATION]);


select * from RRHH_OCUPATIONAL_HEALTH_MEDICATIONS_LOTS;