---FUNCTION GET CAMPANY
GO 
CREATE FUNCTION dbo.fnGetCompanyIdByName(
 @CompanyName NVARCHAR(200)
)
RETURNS UNIQUEIDENTIFIER
AS 
BEGIN
  DECLARE @IdeCompany UNIQUEIDENTIFIER;
  IF(@CompanyName IS NULL)
    RETURN NULL;

   SELECT @IdeCompany = IDE_COMPANY  FROM SYS_COMPANIES
   WHERE NAME = @CompanyName;

   IF @IdeCompany IS NULL 
   RETURN NULL;

   RETURN @IdeCompany;
END;
GO 
-- 
GO 
CREATE FUNCTION dbo.fnGetCompanyIdByNif(
  @Nif NVARCHAR(15)
)
RETURNS UNIQUEIDENTIFIER
AS 
BEGIN
  DECLARE @IdeCompany UNIQUEIDENTIFIER;

  IF @Nif IS NULL
    RETURN NULL;

   SELECT @IdeCompany = IDE_COMPANY  FROM SYS_COMPANIES WHERE NIF = @Nif;

   IF @IdeCompany IS NULL 
   RETURN NULL;

   RETURN @IdeCompany;
END;
GO 

SELECT dbo.fnGetCompanyIdByName('FLORES LATITUD CERO CIA. LTDA.') AS "IDE_COMPANY";
SELECT dbo.fnGetCompanyIdByNif('1791340728001') AS "IDE_COMPANY";