-- Eliminar tablas si existen
IF OBJECT_ID('RRHH_OCUPATIONAL_HEALTH_PERSONNEL', 'U') IS NOT NULL
    DROP TABLE [RRHH_OCUPATIONAL_HEALTH_PERSONNEL];
GO

IF OBJECT_ID('RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF', 'U') IS NOT NULL
    DROP TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF];
GO

IF OBJECT_ID('RRHH_OCUPATIONAL_HEALTH_DISPENSERS', 'U') IS NOT NULL
    DROP TABLE [RRHH_OCUPATIONAL_HEALTH_DISPENSERS];
GO

IF OBJECT_ID('RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS', 'U') IS NOT NULL
    DROP TABLE [RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS];
GO

IF OBJECT_ID('T_RRHH_OCUPATIONAL_HEALTH_MEDICATION_CATEGORIES', 'U') IS NOT NULL
    DROP TABLE [T_RRHH_OCUPATIONAL_HEALTH_MEDICATION_CATEGORIES];
GO

IF OBJECT_ID('T_RRHH_OCUPATIONAL_HEALTH_UNITS', 'U') IS NOT NULL
    DROP TABLE [T_RRHH_OCUPATIONAL_HEALTH_UNITS];
GO

IF OBJECT_ID('T_RRHH_OCUPATIONAL_HEALTH_DOSAGES', 'U') IS NOT NULL
    DROP TABLE [T_RRHH_OCUPATIONAL_HEALTH_DOSAGES];
GO

IF OBJECT_ID('T_RRHH_OCUPATIONAL_HEALTH_MANUFACTURERS', 'U') IS NOT NULL
    DROP TABLE [T_RRHH_OCUPATIONAL_HEALTH_MANUFACTURERS];
GO

IF OBJECT_ID('T_RRHH_OCUPATIONAL_HEALTH_PRESENTATIONS', 'U') IS NOT NULL
    DROP TABLE [T_RRHH_OCUPATIONAL_HEALTH_PRESENTATIONS];
GO

IF OBJECT_ID('T_RRHH_OCUPATIONAL_HEALTH_LOTS', 'U') IS NOT NULL
    DROP TABLE [T_RRHH_OCUPATIONAL_HEALTH_LOTS];
GO

IF OBJECT_ID('T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS', 'U') IS NOT NULL
    DROP TABLE [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS];
GO

IF OBJECT_ID('RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES', 'U') IS NOT NULL
    DROP TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES];
GO

IF OBJECT_ID('RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARE_DETAILS', 'U') IS NOT NULL
    DROP TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARE_DETAILS];
GO

IF OBJECT_ID('RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS', 'U') IS NOT NULL
    DROP TABLE [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS];
GO

IF OBJECT_ID('RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_DETAILS', 'U') IS NOT NULL
    DROP TABLE [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_DETAILS];
GO

IF OBJECT_ID('RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS', 'U') IS NOT NULL
    DROP TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS];
GO

IF OBJECT_ID('RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS_DETAILS', 'U') IS NOT NULL
    DROP TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS_DETAILS];
GO


CREATE TABLE [RRHH_OCUPATIONAL_HEALTH_PERSONNEL] (
  [IDE_PERSONNEL] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_COMPANY] uniqueidentifier NOT NULL,
  [IDE_GENDER] uniqueidentifier NOT NULL,
  [DNI] VARCHAR(30) CHECK (LEN(DNI) >= 10 AND LEN(DNI) <=30) UNIQUE NOT NULL,
  [FIRST_NAME] VARCHAR(65) CHECK (LEN(FIRST_NAME) >= 2 AND LEN(FIRST_NAME) <= 65) NOT NULL,
  [LAST_NAME] VARCHAR(65) CHECK (LEN(LAST_NAME) >= 2 AND LEN(LAST_NAME) <= 65) NOT NULL,
  [PHONE] VARCHAR(35),
  [PHOTO] VARBINARY(MAX),
  [EMAIL] VARCHAR(255) CHECK (EMAIL LIKE '%_@__%.__%') UNIQUE,
  [BIRTH_DATE] DATE,
  [STATUS] nvarchar(255) NOT NULL CHECK ([STATUS] IN ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'RETIRED')) DEFAULT ('ACTIVE'),
  [IS_DELETED] BIT  NOT NULL DEFAULT (0)
)
GO


CREATE TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF] (
  [IDE_MEDICAL_STAFF] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_COMPANY] uniqueidentifier NOT NULL,
  [MEDICAL_STAFF_CODE] VARCHAR(45) CHECK(LEN(MEDICAL_STAFF_CODE) >= 2 AND LEN(MEDICAL_STAFF_CODE) <= 45) UNIQUE NOT NULL
)
GO


CREATE TABLE [RRHH_OCUPATIONAL_HEALTH_DISPENSERS] (
  [IDE_DISPENSER] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_COMPANY] uniqueidentifier NOT NULL,
  [DISPENSER_CODE] VARCHAR(45) CHECK(LEN(DISPENSER_CODE) >= 2 AND LEN(DISPENSER_CODE) <= 45) UNIQUE NOT NULL
)
GO


CREATE TABLE [RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS] (
  [IDE_ASSIGNMENT] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_COMPANY] uniqueidentifier NOT NULL,
  [IDE_ENTITY] uniqueidentifier NOT NULL,
  [ASSIGNMENT_TYPE] nvarchar(255) NOT NULL CHECK ([ASSIGNMENT_TYPE] IN ('MEDICAL', 'DISPENSER')),
  [ACTIVE] BIT NOT NULL DEFAULT (1)
)
GO


CREATE TABLE [T_RRHH_OCUPATIONAL_HEALTH_MEDICATION_CATEGORIES] (
  [IDE_CATEGORY] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_COMPANY] uniqueidentifier NOT NULL,
  [CATEGORY_NAME] VARCHAR(150) CHECK(LEN(CATEGORY_NAME) >= 2 AND LEN(CATEGORY_NAME) <= 150) UNIQUE NOT NULL
)
GO

CREATE TABLE [T_RRHH_OCUPATIONAL_HEALTH_UNITS] (
  [IDE_UNIT] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_COMPANY] uniqueidentifier NOT NULL,
  [UNIT_NAME] VARCHAR(50) CHECK(LEN(UNIT_NAME) >= 2 AND LEN(UNIT_NAME) <= 50) UNIQUE NOT NULL
)
GO

CREATE TABLE [T_RRHH_OCUPATIONAL_HEALTH_DOSAGES] (
  [IDE_DOSAGE] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_COMPANY] uniqueidentifier NOT NULL,
  [DOSAGE_NAME] VARCHAR(50) CHECK(LEN(DOSAGE_NAME) >= 2 AND LEN(DOSAGE_NAME) <= 50) UNIQUE NOT NULL
)
GO

CREATE TABLE [T_RRHH_OCUPATIONAL_HEALTH_MANUFACTURERS] (
  [IDE_MANUFACTURER] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_COMPANY] uniqueidentifier NOT NULL,
  [MANUFACTURER_NAME] VARCHAR(50) CHECK(LEN(MANUFACTURER_NAME) >= 2 AND LEN(MANUFACTURER_NAME) <= 50) UNIQUE NOT NULL
)
GO

CREATE TABLE [T_RRHH_OCUPATIONAL_HEALTH_PRESENTATIONS] (
  [IDE_PRESENTATION] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_COMPANY] uniqueidentifier NOT NULL,
  [PRESENTATION_NAME] VARCHAR(50) CHECK(LEN(PRESENTATION_NAME) >= 2 AND LEN(PRESENTATION_NAME) <= 50) UNIQUE NOT NULL
)
GO

CREATE TABLE [T_RRHH_OCUPATIONAL_HEALTH_LOTS] (
  [IDE_LOT] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_COMPANY] uniqueidentifier NOT NULL,
  [LOT_NUMBER] VARCHAR(50) UNIQUE NOT NULL,
  [MANUFACTURE_DATE] DATE NOT NULL,
  [EXPIRATION_DATE] DATE NOT NULL,
  CHECK ([EXPIRATION_DATE] > [MANUFACTURE_DATE])
)
GO

CREATE TABLE [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS] (
  [IDE_MEDICATION] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_COMPANY] uniqueidentifier NOT NULL,
  [IDE_CATEGORY] uniqueidentifier,
  [IDE_UNIT] uniqueidentifier,
  [IDE_DOSAGE] uniqueidentifier,
  [IDE_MANUFACTURER] uniqueidentifier,
  [IDE_PRESENTATION] uniqueidentifier,
  [IDE_LOT] uniqueidentifier,
  [MEDICATION_NAME] VARCHAR(200) CHECK(LEN(MEDICATION_NAME) >= 1 AND LEN(MEDICATION_NAME) <= 200) NOT NULL,
  [DESCRIPTION] VARCHAR(1000),
  [STATUS] nvarchar(255) NOT NULL CHECK ([STATUS] IN ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'DISCONTINUED')) DEFAULT ('ACTIVE'),
  [IS_DELETED] BIT NOT NULL DEFAULT (1)
)
GO


CREATE TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES] (
  [IDE_MEDICAL_CARE] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_COMPANY] uniqueidentifier NOT NULL,
  [IDE_EMPLOYEE] uniqueidentifier NOT NULL,
  [IDE_MEDICAL_STAFF] uniqueidentifier NOT NULL,
  [MEDICAL_CARE_CODE] VARCHAR(45) CHECK(LEN(MEDICAL_CARE_CODE) >= 2 AND LEN(MEDICAL_CARE_CODE) <= 45) UNIQUE NOT NULL,
  [REASON_FOR_VISIT] VARCHAR(100),
  [ATTENTION_DATE] DATETIME NOT NULL CHECK (ATTENTION_DATE <= GETDATE()),
  [STATUS] nvarchar(255) NOT NULL CHECK ([STATUS] IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE')),
  [IS_DELETED] BIT  NOT NULL DEFAULT (1)
)
GO


CREATE TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARE_DETAILS] (
  [IDE_MEDICAL_CARE_DETAIL] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_MEDICAL_CARE] uniqueidentifier NOT NULL,
  [DIAGNOSIS] VARCHAR(1000) CHECK(LEN(DIAGNOSIS) >= 2 AND LEN(DIAGNOSIS) <= 1000) NOT NULL,
  [SYMPTOMS] VARCHAR(1000) CHECK(LEN(SYMPTOMS) >= 2 AND LEN(SYMPTOMS) <= 1000) NOT NULL,
  [PROCEDURES_PERFORMED] VARCHAR(100),
  [REST_HOURS] INT CHECK (REST_HOURS >= 0) DEFAULT (0),
  [INSTITUTION] VARCHAR(100),
  [MEDICAL_CERTIFICATE_PRESENT] BIT DEFAULT (0),
  [FOLLOW_UP_REQUIRED] BIT DEFAULT (0),
  [FOLLOW_UP_DATE] DATETIME,
  [FOLLOW_UP_STATUS] nvarchar(255) NOT NULL CHECK ([FOLLOW_UP_STATUS] IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE')),
  [ADDITIONAL_NOTES] VARCHAR(MAX)
)
GO

CREATE TABLE [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS] (
  [IDE_PRESCRIPTION] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_COMPANY] uniqueidentifier NOT NULL,
  [IDE_MEDICAL_CARE] uniqueidentifier NOT NULL,
  [PRESCRIPTION_CODE] VARCHAR(45) UNIQUE NOT NULL,
  [PRESCRIPTION_DATE] DATE NOT NULL CHECK (PRESCRIPTION_DATE <= GETDATE()),
  [PRESCRIPTION_NOTES] VARCHAR(1000),
  [STATUS] nvarchar(255) NOT NULL CHECK ([STATUS] IN ('ISSUED', 'IN_PROGRESS', 'DISPENSED', 'CANCELLED')) DEFAULT ('ISSUED'),
  [IS_DELETED] BIT  NOT NULL DEFAULT (0)
)
GO

CREATE TABLE [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_DETAILS] (
  [IDE_PRESCRIPTION_DETAIL] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_PRESCRIPTION] uniqueidentifier NOT NULL,
  [IDE_MEDICATION] uniqueidentifier NOT NULL,
  [DOSAGE] VARCHAR(50),
  [QUANTITY] INT CHECK (QUANTITY > 0) NOT NULL DEFAULT (1),
  [ADMINISTRATION_ROUTE] VARCHAR(50),
  [FREQUENCY] VARCHAR(50),
  [DURATION] VARCHAR(50),
  [INSTRUCTIONS] VARCHAR(1000)
)
GO


CREATE TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS] (
  [IDE_MEDICATION_DISPENSING] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_COMPANY] uniqueidentifier NOT NULL,
  [IDE_EMPLOYEE] uniqueidentifier NOT NULL,
  [IDE_PRESCRIPTION] uniqueidentifier NOT NULL,
  [IDE_ASSIGNMENT] uniqueidentifier NOT NULL,
  [DISPENSING_CODE] VARCHAR(45) CHECK(LEN(DISPENSING_CODE) >= 2 AND LEN(DISPENSING_CODE) <= 45) UNIQUE NOT NULL,
  [DISPENSING_DATE] DATE NOT NULL CHECK (DISPENSING_DATE <= GETDATE()),
  [DISCOUNT] DECIMAL(5,2) CHECK (DISCOUNT >= 0) DEFAULT (0.00),
  [STATUS] nvarchar(255) NOT NULL CHECK ([STATUS] IN ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'DISCONTINUED')) DEFAULT ('ACTIVE'),
  [IS_DELETED] BIT  NOT NULL DEFAULT (0)
)
GO


CREATE TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS_DETAILS] (
  [IDE_MEDICATION_DISPENSING_DETAILS] uniqueidentifier PRIMARY KEY NOT NULL DEFAULT (newid()),
  [IDE_MEDICATION_DISPENSING] uniqueidentifier NOT NULL,
  [IDE_MEDICATION] uniqueidentifier NOT NULL,
  [QUANTITY] INT CHECK(QUANTITY >= 1) NOT NULL DEFAULT (1)
)
GO


-- RRHH_OCUPATIONAL_HEALTH_PERSONNEL
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_PERSONNEL_index_2] ON [RRHH_OCUPATIONAL_HEALTH_PERSONNEL] ("LAST_NAME", "FIRST_NAME", "STATUS")
GO


-- RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS_index_5] ON [RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS] ("IDE_ENTITY")
GO
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS_index_6] ON [RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS] ("ASSIGNMENT_TYPE")
GO

-- T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS
CREATE INDEX [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS_index_7] ON [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS] ("STATUS")
GO
CREATE INDEX [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS_index_8] ON [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS] ("MEDICATION_NAME")
GO
CREATE INDEX [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS_index_9] ON [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS] ("IDE_LOT")
GO

-- RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES_index_10] ON [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES] ("IDE_EMPLOYEE", "ATTENTION_DATE")
GO
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES_index_11] ON [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES] ("STATUS")
GO

-- RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARE_DETAILS
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARE_DETAILS_index_13] ON [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARE_DETAILS] ("IDE_MEDICAL_CARE")
GO
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARE_DETAILS_index_14] ON [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARE_DETAILS] ("FOLLOW_UP_DATE")
GO
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARE_DETAILS_index_15] ON [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARE_DETAILS] ("FOLLOW_UP_STATUS")
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARE_DETAILS_index_16] ON [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARE_DETAILS] ("DIAGNOSIS");
GO

-- RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_index_17] ON [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS] ("IDE_MEDICAL_CARE")
GO
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_index_18] ON [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS] ("STATUS")
GO
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_index_19] ON [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS] ("PRESCRIPTION_DATE")
GO

-- RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_DETAILS
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_DETAILS_index_20] ON [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_DETAILS] ("IDE_PRESCRIPTION")
GO
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_DETAILS_index_21] ON [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_DETAILS] ("IDE_MEDICATION")
GO

-- RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS_index_22] ON [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS] ("IDE_EMPLOYEE", "DISPENSING_DATE")
GO
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS_index_23] ON [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS] ("STATUS")
GO
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS_index_24] ON [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS] ("IDE_PRESCRIPTION")
GO

-- RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS_DETAILS
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS_DETAILS_index_25] ON [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS_DETAILS] ("IDE_MEDICATION_DISPENSING")
GO
CREATE INDEX [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS_DETAILS_index_26] ON [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS_DETAILS] ("IDE_MEDICATION")
GO



ALTER TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF] ADD FOREIGN KEY ([IDE_MEDICAL_STAFF]) REFERENCES [RRHH_OCUPATIONAL_HEALTH_PERSONNEL] ([IDE_PERSONNEL])
GO

ALTER TABLE [RRHH_OCUPATIONAL_HEALTH_DISPENSERS] ADD FOREIGN KEY ([IDE_DISPENSER]) REFERENCES [RRHH_OCUPATIONAL_HEALTH_PERSONNEL] ([IDE_PERSONNEL])
GO

ALTER TABLE [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS] ADD FOREIGN KEY ([IDE_CATEGORY]) REFERENCES [T_RRHH_OCUPATIONAL_HEALTH_MEDICATION_CATEGORIES] ([IDE_CATEGORY])
GO

ALTER TABLE [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS] ADD FOREIGN KEY ([IDE_UNIT]) REFERENCES [T_RRHH_OCUPATIONAL_HEALTH_UNITS] ([IDE_UNIT])
GO

ALTER TABLE [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS] ADD FOREIGN KEY ([IDE_DOSAGE]) REFERENCES [T_RRHH_OCUPATIONAL_HEALTH_DOSAGES] ([IDE_DOSAGE])
GO

ALTER TABLE [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS] ADD FOREIGN KEY ([IDE_MANUFACTURER]) REFERENCES [T_RRHH_OCUPATIONAL_HEALTH_MANUFACTURERS] ([IDE_MANUFACTURER])
GO

ALTER TABLE [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS] ADD FOREIGN KEY ([IDE_PRESENTATION]) REFERENCES [T_RRHH_OCUPATIONAL_HEALTH_PRESENTATIONS] ([IDE_PRESENTATION])
GO

ALTER TABLE [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS] ADD FOREIGN KEY ([IDE_LOT]) REFERENCES [T_RRHH_OCUPATIONAL_HEALTH_LOTS] ([IDE_LOT])
GO

ALTER TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES] ADD FOREIGN KEY ([IDE_EMPLOYEE]) REFERENCES [RRHH_OCUPATIONAL_HEALTH_PERSONNEL] ([IDE_PERSONNEL])
GO

ALTER TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES] ADD FOREIGN KEY ([IDE_MEDICAL_STAFF]) REFERENCES [RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF] ([IDE_MEDICAL_STAFF])
GO

ALTER TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARE_DETAILS] ADD FOREIGN KEY ([IDE_MEDICAL_CARE]) REFERENCES [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES] ([IDE_MEDICAL_CARE])
GO

ALTER TABLE [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS] ADD FOREIGN KEY ([IDE_MEDICAL_CARE]) REFERENCES [RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES] ([IDE_MEDICAL_CARE])
GO

ALTER TABLE [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_DETAILS] ADD FOREIGN KEY ([IDE_PRESCRIPTION]) REFERENCES [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS] ([IDE_PRESCRIPTION])
GO

ALTER TABLE [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_DETAILS] ADD FOREIGN KEY ([IDE_MEDICATION]) REFERENCES [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS] ([IDE_MEDICATION])
GO

ALTER TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS] ADD FOREIGN KEY ([IDE_EMPLOYEE]) REFERENCES [RRHH_OCUPATIONAL_HEALTH_PERSONNEL] ([IDE_PERSONNEL])
GO

ALTER TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS] ADD FOREIGN KEY ([IDE_PRESCRIPTION]) REFERENCES [RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS] ([IDE_PRESCRIPTION])
GO

ALTER TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS] ADD FOREIGN KEY ([IDE_ASSIGNMENT]) REFERENCES [RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS] ([IDE_ASSIGNMENT])
GO

ALTER TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS_DETAILS] ADD FOREIGN KEY ([IDE_MEDICATION_DISPENSING]) REFERENCES [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS] ([IDE_MEDICATION_DISPENSING])
GO

ALTER TABLE [RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS_DETAILS] ADD FOREIGN KEY ([IDE_MEDICATION]) REFERENCES [T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS] ([IDE_MEDICATION])
GO
