-- CREATE DATA BASE
-- Drop existing tables if they exist
IF EXISTS (SELECT 1 FROM sysobjects WHERE id = OBJECT_ID('T_RRHH_OCUPATIONAL_HEALTH_DISPENSERS') AND type = 'U')
    DROP TABLE T_RRHH_OCUPATIONAL_HEALTH_DISPENSERS;
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = OBJECT_ID('RRHH_OCUPATIONAL_HEALTH_DISPENSING_DETAILS') AND type = 'U')
    DROP TABLE RRHH_OCUPATIONAL_HEALTH_DISPENSING_DETAILS;
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = OBJECT_ID('RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES') AND type = 'U')
    DROP TABLE RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES;
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = OBJECT_ID('T_RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF') AND type = 'U')
    DROP TABLE T_RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF;
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = OBJECT_ID('T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS') AND type = 'U')
    DROP TABLE T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS;
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = OBJECT_ID('RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS') AND type = 'U')
    DROP TABLE RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS;
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = OBJECT_ID('RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS') AND type = 'U')
    DROP TABLE RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS;
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = OBJECT_ID('RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_DETAILS') AND type = 'U')
    DROP TABLE RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_DETAILS;
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = OBJECT_ID('T_RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS') AND type = 'U')
    DROP TABLE T_RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS;
GO


CREATE TABLE T_RRHH_OCUPATIONAL_HEALTH_DISPENSERS (
    IDE_DISPENSER UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    IDE_COMPANY UNIQUEIDENTIFIER NOT NULL,
    IDE_MEDICAL_STAFF UNIQUEIDENTIFIER NULL,
    FIRST_NAME VARCHAR(65) NOT NULL,
    LAST_NAME VARCHAR(65) NOT NULL,
    DNI VARCHAR(30) CHECK (LEN(DNI) >= 10) NOT NULL UNIQUE,
    PHONE VARCHAR(35) CHECK (LEN(PHONE) >= 10),
    DISPENSER_PHOTO IMAGE NULL,
    EMAIL VARCHAR(255) CHECK (EMAIL LIKE '%@%.%') UNIQUE,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F', 'X')) NOT NULL,
    STATUS BIT CHECK (STATUS IN (0, 1)) NOT NULL,
    IS_DELETED BIT CHECK (IS_DELETED IN (0, 1)) NOT NULL,
    CONSTRAINT PK_T_RRHH_MED_DISPENSINGS PRIMARY KEY (IDE_DISPENSER)
);
GO

CREATE TABLE RRHH_OCUPATIONAL_HEALTH_DISPENSING_DETAILS (
    IDE_DISPENSING_DETAIL UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    IDE_COMPANY UNIQUEIDENTIFIER NOT NULL,
    IDE_MEDICATION UNIQUEIDENTIFIER NULL,
    IDE_DISPENSING UNIQUEIDENTIFIER NULL,
    QUANTITY INT CHECK (QUANTITY >= 0) NOT NULL,
    DISPENSING_DATE DATE NOT NULL,
    CONSTRAINT PK_RRHH_OCUPATIONAL_HEALTH_DISP PRIMARY KEY (IDE_DISPENSING_DETAIL)
);
GO

CREATE TABLE RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES (
    IDE_MEDICAL_CARE UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    IDE_COMPANY UNIQUEIDENTIFIER NOT NULL,
    IDE_MEDICAL_STAFF UNIQUEIDENTIFIER NULL,
    IDE_EMPLOYEE UNIQUEIDENTIFIER NOT NULL,
    MEDICAL_CARE_CODE VARCHAR(45) NOT NULL UNIQUE,
    DIAGNOSIS VARCHAR(1000) NOT NULL,
    SYMPTOMS VARCHAR(1000) NOT NULL,
    ATTENTION_DATE DATETIME NOT NULL,
    REST_HOURS INT CHECK (REST_HOURS >= 0),
    INSTITUTION VARCHAR(100) NULL,
    FOLLOW_UP_REQUIRED BIT NULL,
    FOLLOW_UP_DATE DATE NULL,
    FOLLOW_UP_STATUS CHAR(1) CHECK (FOLLOW_UP_STATUS IN ('P', 'I', 'C')),
    MEDICAL_CERTIFICATE_PRESENT BIT NULL,
    STATUS VARBINARY(25) NOT NULL,
    IS_DELETED BIT CHECK (IS_DELETED IN (0, 1)) NOT NULL,
    CONSTRAINT PK_RRHH_OCUP_MEDICAL_CARES PRIMARY KEY (IDE_MEDICAL_CARE)
);
GO

CREATE TABLE T_RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF (
    IDE_MEDICAL_STAFF UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    IDE_COMPANY UNIQUEIDENTIFIER NOT NULL,
    DNI VARCHAR(30) CHECK (LEN(DNI) >= 10) NOT NULL UNIQUE,
    MEDICAL_STAFF_CODE VARCHAR(45) NOT NULL UNIQUE ,
    FIRST_NAME VARCHAR(65) NOT NULL,
    LAST_NAME VARCHAR(65) NOT NULL,
    PHONE VARCHAR(35) NULL,
    MEDICAL_STAFF_PHOTO IMAGE NULL,
    EMAIL VARCHAR(255) CHECK (EMAIL LIKE '%@%.%') UNIQUE,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F', 'X')) NOT NULL,
    STATUS BIT CHECK (STATUS IN (0, 1)) NOT NULL,
    IS_DELETED BIT CHECK (IS_DELETED IN (0, 1)) NOT NULL,
    CONSTRAINT PK_T_RRHH_OCUP_MEDICAL_STAFF PRIMARY KEY (IDE_MEDICAL_STAFF)
);
GO

CREATE TABLE T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS (
    IDE_MEDICATION UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    IDE_COMPANY UNIQUEIDENTIFIER NOT NULL,
    MEDICATION_NAME VARCHAR(200) NOT NULL,
    EXPIRATION_DATE DATE NOT NULL,
    DESCRIPTION VARCHAR(1000) NULL,
    MEDICATION_CATEGORY VARCHAR(150) NULL,
    UNIT_MEASUREMENT VARCHAR(50) NULL,
    DOSAGE VARCHAR(50) NULL,
    STATUS BIT CHECK (STATUS IN (0, 1)) NOT NULL,
    IS_DELETED BIT CHECK (IS_DELETED IN (0, 1)) NOT NULL,
    CONSTRAINT PK_T_RRHH_OCUP_MEDICATIONS PRIMARY KEY (IDE_MEDICATION)
);
GO

CREATE TABLE RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS (
    IDE_DISPENSING UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    IDE_COMPANY UNIQUEIDENTIFIER NOT NULL,
    IDE_DISPENSER UNIQUEIDENTIFIER NULL,
    IDE_EMPLOYEE UNIQUEIDENTIFIER NOT NULL,
    DISPENSING_CODE VARCHAR(45) NOT NULL UNIQUE,
    DISPENSING_DATE DATE NOT NULL,
    DISCOUNT DECIMAL(18,2) CHECK (DISCOUNT >= 0),
    STATUS CHAR(1) CHECK (STATUS IN ('A', 'I', 'S')) NOT NULL, -- 'A' para 'Active', 'I' para 'Inactive', 'S' para 'Suspended'
    IS_DELETED BIT CHECK (IS_DELETED IN (0, 1)) NOT NULL,
    CONSTRAINT PK_RRHH_OCUP_MEDICATION_DISPENSINGS PRIMARY KEY (IDE_DISPENSING)
);
GO

CREATE TABLE RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS (
    IDE_PRESCRIPTION UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    IDE_COMPANY UNIQUEIDENTIFIER NOT NULL,
    IDE_MEDICAL_CARE UNIQUEIDENTIFIER NULL,
    PRESCRIPTION_CODE VARCHAR(45) NOT NULL UNIQUE ,
    PRESCRIPTION_DATE DATE NOT NULL,
    PRESCRIPTION_NOTES VARCHAR(1000) NULL,
    STATUS BIT CHECK (STATUS IN (0, 1)) NOT NULL,
    IS_DELETED BIT CHECK (IS_DELETED IN (0, 1)) NOT NULL,
    CONSTRAINT PK_RRHH_OCUP_PRESCRIPTIONS PRIMARY KEY (IDE_PRESCRIPTION)
);
GO

CREATE TABLE RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_DETAILS (
    IDE_PRESCRIPTION_DETAIL UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    IDE_COMPANY UNIQUEIDENTIFIER NOT NULL,
    IDE_PRESCRIPTION UNIQUEIDENTIFIER NULL,
    IDE_MEDICATION UNIQUEIDENTIFIER NULL,
    PRESCRIPTION_GUIDELINES VARCHAR(1000) NOT NULL,
    PRESCRIBED_QUANTITY INT CHECK (PRESCRIBED_QUANTITY >= 0) NOT NULL,
    DOSAGE VARCHAR(50) NULL,
    FREQUENCY VARCHAR(50) NULL,
    DURATION VARCHAR(50) NULL,
    CONSTRAINT PK_RRHH_OCUP_PRESCRIPTIONS_DETAILS PRIMARY KEY (IDE_PRESCRIPTION_DETAIL)
);
GO

CREATE TABLE T_RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS (
    IDE_ASSIGNMENT UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    IDE_COMPANY UNIQUEIDENTIFIER NOT NULL,
    ENTITY_TYPE CHAR(1) CHECK (ENTITY_TYPE IN ('D', 'M')) NOT NULL, -- 'D' para 'DISPENSER', 'M' para 'MEDICAL_STAFF'
    IDE_ENTITY UNIQUEIDENTIFIER NOT NULL, -- ID del dispensador o personal médico
    CONSTRAINT PK_T_RRHH_OCUP_ASSIGNMENTS PRIMARY KEY (IDE_ASSIGNMENT),
    CONSTRAINT CHK_T_RRHH_OCUPATIONAL_HEALTH_ASSIGNMENTS_ENTITY_TYPE CHECK (
        (ENTITY_TYPE = 'D' AND IDE_ENTITY IN (SELECT IDE_DISPENSER FROM T_RRHH_OCUPATIONAL_HEALTH_DISPENSERS))
        OR
        (ENTITY_TYPE = 'M' AND IDE_ENTITY IN (SELECT IDE_MEDICAL_STAFF FROM T_RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF))
    )
);
GO


-- Add foreign key constraints
ALTER TABLE T_RRHH_OCUPATIONAL_HEALTH_DISPENSERS
    ADD CONSTRAINT FK_DISPENSERS_MEDICAL_STAFF FOREIGN KEY (IDE_MEDICAL_STAFF)
        REFERENCES T_RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF (IDE_MEDICAL_STAFF);
GO

ALTER TABLE RRHH_OCUPATIONAL_HEALTH_DISPENSING_DETAILS
    ADD CONSTRAINT FK_DISPENSING_DETAILS_MEDICATIONS FOREIGN KEY (IDE_MEDICATION)
        REFERENCES T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS (IDE_MEDICATION);
GO

ALTER TABLE RRHH_OCUPATIONAL_HEALTH_DISPENSING_DETAILS
    ADD CONSTRAINT FK_DISPENSING_DETAILS_DISPENSINGS FOREIGN KEY (IDE_DISPENSING)
        REFERENCES RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS (IDE_DISPENSING);
GO

ALTER TABLE RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES
    ADD CONSTRAINT FK_MEDICAL_CARES_MEDICAL_STAFF FOREIGN KEY (IDE_MEDICAL_STAFF)
        REFERENCES T_RRHH_OCUPATIONAL_HEALTH_MEDICAL_STAFF (IDE_MEDICAL_STAFF);
GO

ALTER TABLE RRHH_OCUPATIONAL_HEALTH_MEDICATION_DISPENSINGS
    ADD CONSTRAINT FK_MEDICATION_DISPENSINGS_DISPENSERS FOREIGN KEY (IDE_DISPENSER)
        REFERENCES T_RRHH_OCUPATIONAL_HEALTH_DISPENSERS (IDE_DISPENSER);
GO

ALTER TABLE RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS
    ADD CONSTRAINT FK_PRESCRIPTIONS_MEDICAL_CARES FOREIGN KEY (IDE_MEDICAL_CARE)
        REFERENCES RRHH_OCUPATIONAL_HEALTH_MEDICAL_CARES (IDE_MEDICAL_CARE);
GO

ALTER TABLE RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_DETAILS
    ADD CONSTRAINT FK_PRESCRIPTIONS_DETAILS_MEDICATIONS FOREIGN KEY (IDE_MEDICATION)
        REFERENCES T_RRHH_OCUPATIONAL_HEALTH_MEDICATIONS (IDE_MEDICATION);
GO

ALTER TABLE RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS_DETAILS
    ADD CONSTRAINT FK_PRESCRIPTIONS_DETAILS_PRESCRIPTIONS FOREIGN KEY (IDE_PRESCRIPTION)
        REFERENCES RRHH_OCUPATIONAL_HEALTH_PRESCRIPTIONS (IDE_PRESCRIPTION);
GO
