-- ADD COLUMNS AND CONSTRAINTS
ALTER TABLE RRHH_OCUPATIONAL_HEALTH_DISPENSERS 
ADD FIRST_NAME VARCHAR(65) NOT NULL,
    LAST_NAME VARCHAR(65) NOT NULL,
    PHONE VARCHAR(35) CHECK (LEN(PHONE) > 9),
    DISPENSER_PHOTO IMAGE,
    EMAIL VARCHAR(255) CHECK (EMAIL LIKE '%@%.%'),
    GENDER VARCHAR(15) NOT NULL;

--HAS PHOTO 1 OR 0
SELECT a.*, 
       CASE WHEN a.DISPENSER_PHOTO IS NOT NULL THEN 1 ELSE 0 END AS HAS_PHOTO
FROM RRHH_OCUPATIONAL_HEALTH_DISPENSERS a;



