-- Active: 1715738880073@@127.0.0.1@5432@playground-db
-- CREATE TABLE
CREATE TABLE USERS_CAR (
    USER_ID SERIAL,
    FIRSTNAME VARCHAR(100) NOT NULL,
    -- Column constraint 
    LASTNAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (USER_ID) -- Table constraint
);

-- INSERT WITH COLUMN NAMES
INSERT INTO
    USERS_CAR (FIRSTNAME, LASTNAME)
VALUES
    ('John', 'Doe');

-- INSERT WITHOUT COLUMN NAMES
INSERT INTO
    USERS_CAR (FIRSTNAME, LASTNAME)
VALUES
    ('An', 'Llerena');

-- INSERT MULTIPLE VALUES
INSERT INTO
    USERS_CAR (FIRSTNAME, LASTNAME)
VALUES
    ('Roberto', 'Pena'),
    ('Gonzalo', 'Silva'),
    ('Fernando', 'Garcia');

-- UPDATE RECORDS
-- If I don't put the WHERE clause, I modify all records.
UPDATE
    USERS_CAR
SET
    FIRSTNAME = 'Pedro',
    LASTNAME = 'Padilla'
WHERE
    USER_ID = 5;

-- SEE  RECORDS WITHE LIMIT 4 OFFSET 1
SELECT
    *
FROM
    USERS_CAR
LIMIT
    4 OFFSET 1;

-- WHERE
SELECT
    *
FROM
    USERS_CAR u
WHERE
    u.USER_ID = 3;

--LIKE: QUE COINCIDA CON EL CARÁCTER
SELECT
    u.FIRSTNAME,
    u.LASTNAME
FROM
    USERS_CAR u
WHERE
    u.FIRSTNAME LIKE '%ohn'
    AND u.LASTNAME LIKE '_oe';

-- DELETE REGISTERS
-- PRIMERO BUSQUEMOS QUE ELIMINAR
-- SI NO USAMOS UN WHERE SE ELIMINARA TODO
SELECT
    *
FROM
    USERS_CAR
WHERE
    USER_ID = 3;

DELETE FROM
    USERS_CAR
WHERE
    USER_ID = 3;

-- DROP TABLE
DROP TABLE USERS_CAR;

-- TRUNCATES
TRUNCATE TABLE USER_CARS;